services:
  - type: web
    name: utsavika-api
    env: node
    plan: free
    buildCommand: cd server && npm install && npm run build
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        value: 0442edc50e0f6d48e9e907a8bbc8f230
      - key: ORDER_NOTIFY_TO
        value: thanayp99@gmail.com
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PASS
        value: fvkbirsskqhdtrjd
      - key: SMTP_PORT
        value: 465
      - key: SMTP_USER
        value: thanayp99@gmail.com
