// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbndyboounbszcwatsuf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZibmR5Ym9vdW5ic3pjd2F0c3VmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNDgwNTEsImV4cCI6MjA3MjcyNDA1MX0.816bzfIvMohnvB6meO721ifbvIE9xY0mQ2dQ_LmPF4Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});